matrix:
  include:
      # BACKEND
    - language: python
      python: 3.6
      before_script:
        - cd Atlas/backend
        - chmod +x test
      script:
        - ./test

      # FRONTEND
    - language: python
      python: 3.6
      before_script:
        - cd Atlas/frontend
        - chmod +x test
      script:
        - ./test

      # ANDROID
    - language: android
      sudo: false
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.gradle/native/
          - $HOME/.gradle/daemon/
      android:
        components:
          - android-26
          - android-17
          - build-tools-26.0.1
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-armeabi-v7a-android-17
      install:
      # Update sdk tools to latest version and install/update components
          - echo yes | sdkmanager "tools"
          - echo yes | sdkmanager "platforms;android-26"
          - echo yes | sdkmanager "extras;android;m2repository"
          - echo yes | sdkmanager "extras;google;m2repository"
          - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
          - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
      before_script:
        - cd Atlas/android
        - chmod +x gradlew
      script:
        - ./gradlew assemble -PdisablePreDex --continue --stacktrace
        - ./gradlew check -PdisablePreDex --continue --stacktrace
      after_script:
          # - echo no | avdmanager create avd --force --name test --package 'system-images;android-17;default;armeabi-v7a' --abi armeabi-v7a
          # - emulator -avd test -no-skin -no-window &
          # - android-wait-for-emulator
          # - adb devices
          # - adb shell input keyevent 82 &
          # - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

notifications:
  email:
    - yigitozkavci8@gmail.com
    - ramazankaniturkmen@gmail.com
    - s.talhanisanci@gmail.com
    - aykut___1995@hotmail.com
    - esref.ozdemir27@gmail.com
